/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Config */
        get: operations["public_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trips */
        get: operations["list_trips_api_trips_get"];
        put?: never;
        /** Create Trip */
        post: operations["create_trip_api_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip */
        get: operations["get_trip_api_trips__trip_id__get"];
        put?: never;
        post?: never;
        /** Delete Trip */
        delete: operations["delete_trip_api_trips__trip_id__delete"];
        options?: never;
        head?: never;
        /** Update Trip */
        patch: operations["update_trip_api_trips__trip_id__patch"];
        trace?: never;
    };
    "/api/trips/{trip_id}/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Days */
        get: operations["list_days_api_trips__trip_id__days_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/days/{day_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Day */
        patch: operations["update_day_api_days__day_id__patch"];
        trace?: never;
    };
    "/api/days/{day_id}/stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Stop
         * @description Crea una tappa e restituisce il giorno aggiornato (tappe + segmenti riallineati).
         */
        post: operations["create_stop_api_days__day_id__stops_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/days/{day_id}/reorder-stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder Stops */
        post: operations["reorder_stops_api_days__day_id__reorder_stops_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stops/{stop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Stop
         * @description Elimina la tappa e restituisce il giorno con posizioni e segmenti riallineati.
         */
        delete: operations["delete_stop_api_stops__stop_id__delete"];
        options?: never;
        head?: never;
        /** Update Stop */
        patch: operations["update_stop_api_stops__stop_id__patch"];
        trace?: never;
    };
    "/api/stops/{stop_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move Stop
         * @description Sposta la tappa in un altro giorno; restituisce i giorni coinvolti.
         */
        post: operations["move_stop_api_stops__stop_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/segments/{segment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Segment */
        patch: operations["update_segment_api_segments__segment_id__patch"];
        trace?: never;
    };
    "/api/trips/{trip_id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Photos */
        get: operations["list_photos_api_trips__trip_id__photos_get"];
        put?: never;
        /** Upload Photos */
        post: operations["upload_photos_api_trips__trip_id__photos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/photos/assign-by-date": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign By Date */
        post: operations["assign_by_date_api_trips__trip_id__photos_assign_by_date_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/photos/{photo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Photo */
        delete: operations["delete_photo_api_photos__photo_id__delete"];
        options?: never;
        head?: never;
        /** Update Photo */
        patch: operations["update_photo_api_photos__photo_id__patch"];
        trace?: never;
    };
    "/api/photos/{photo_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Photo File */
        get: operations["photo_file_api_photos__photo_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Share */
        get: operations["get_share_api_trips__trip_id__share_get"];
        put?: never;
        /**
         * Enable Share
         * @description Attiva il link pubblico; se esiste già lo mantiene.
         */
        post: operations["enable_share_api_trips__trip_id__share_post"];
        /** Disable Share */
        delete: operations["disable_share_api_trips__trip_id__share_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/share/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate Share
         * @description Genera un nuovo link: quello precedente smette di funzionare.
         */
        post: operations["rotate_share_api_trips__trip_id__share_rotate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/share/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shared Trip */
        get: operations["shared_trip_api_share__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/share/{token}/photos/{photo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shared Photo */
        get: operations["shared_photo_api_share__token__photos__photo_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geocode/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_geocode_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssignByDateResult */
        AssignByDateResult: {
            /** Assigned */
            assigned: number;
        };
        /** Body_upload_photos_api_trips__trip_id__photos_post */
        Body_upload_photos_api_trips__trip_id__photos_post: {
            /**
             * Files
             * @description Una o più immagini
             */
            files: string[];
            /** Day Id */
            day_id?: string | null;
            /** Stop Id */
            stop_id?: string | null;
        };
        /** DayOut */
        DayOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Day Number */
            day_number: number;
            /** Title */
            title: string | null;
            /** Notes */
            notes: string | null;
            /** Stops */
            stops: components["schemas"]["StopOut"][];
            /** Segments */
            segments: components["schemas"]["SegmentOut"][];
        };
        /** DayUpdate */
        DayUpdate: {
            /** Title */
            title?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MoveStop */
        MoveStop: {
            /**
             * Day Id
             * Format: uuid
             */
            day_id: string;
            /** Position */
            position?: number | null;
        };
        /** PhotoOut */
        PhotoOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /** Day Id */
            day_id: string | null;
            /** Stop Id */
            stop_id: string | null;
            /** Original Filename */
            original_filename: string;
            /** Mime Type */
            mime_type: string;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Taken At
             * @description Ora locale di scatto (EXIF), senza fuso
             */
            taken_at: string | null;
            /** Taken At Offset */
            taken_at_offset: string | null;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Caption */
            caption: string | null;
            /** Thumb Url */
            thumb_url: string;
            /** Display Url */
            display_url: string;
            /** Original Url */
            original_url: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * PhotoUpdate
         * @description Associazione manuale. Se si indica una tappa, il giorno diventa quello della tappa.
         */
        PhotoUpdate: {
            /** Day Id */
            day_id?: string | null;
            /** Stop Id */
            stop_id?: string | null;
            /** Caption */
            caption?: string | null;
        };
        /** PhotoUploadResult */
        PhotoUploadResult: {
            /** Created */
            created: components["schemas"]["PhotoOut"][];
            /**
             * Duplicates
             * @description Foto già presenti nel viaggio (stesso file)
             */
            duplicates: components["schemas"]["PhotoOut"][];
            /** Errors */
            errors: components["schemas"]["UploadError"][];
        };
        /** PlaceOut */
        PlaceOut: {
            /** Name */
            name: string;
            /** Address */
            address: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            category: components["schemas"]["StopCategory"] | null;
            /** External Ref */
            external_ref: string | null;
        };
        /** PublicConfig */
        PublicConfig: {
            /** Map Style Url */
            map_style_url: string;
            /** Map Attribution */
            map_attribution: string;
            /** Geocoder */
            geocoder: string;
            /** Version */
            version: string;
        };
        /** ReorderStops */
        ReorderStops: {
            /** Stop Ids */
            stop_ids: string[];
        };
        /** SegmentOut */
        SegmentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Day Id
             * Format: uuid
             */
            day_id: string;
            /**
             * From Stop Id
             * Format: uuid
             */
            from_stop_id: string;
            /**
             * To Stop Id
             * Format: uuid
             */
            to_stop_id: string;
            transport_mode: components["schemas"]["TransportMode"];
            /** Planned Duration Min */
            planned_duration_min: number | null;
            /** Actual Duration Min */
            actual_duration_min: number | null;
            /** Distance M */
            distance_m: number | null;
            /** Geometry */
            geometry: [
                number,
                number
            ][] | null;
            /** Notes */
            notes: string | null;
        };
        /** SegmentUpdate */
        SegmentUpdate: {
            transport_mode?: components["schemas"]["TransportMode"] | null;
            /** Planned Duration Min */
            planned_duration_min?: number | null;
            /** Actual Duration Min */
            actual_duration_min?: number | null;
            /** Distance M */
            distance_m?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** ShareInfo */
        ShareInfo: {
            visibility: components["schemas"]["Visibility"];
            /** Token */
            token: string | null;
            /**
             * Path
             * @description Percorso della pagina pubblica, es. /share/{token}
             */
            path: string | null;
            /**
             * Url
             * @description URL completo se PUBLIC_BASE_URL è configurato
             */
            url: string | null;
        };
        /** SharedDay */
        SharedDay: {
            /** Day Number */
            day_number: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Title */
            title: string | null;
            /** Notes */
            notes: string | null;
            /** Stops */
            stops: components["schemas"]["SharedStop"][];
            /** Segments */
            segments: components["schemas"]["SharedSegment"][];
            /** Photos */
            photos: components["schemas"]["SharedPhoto"][];
        };
        /** SharedPhoto */
        SharedPhoto: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Stop Id */
            stop_id: string | null;
            /** Caption */
            caption: string | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /**
             * Taken Time
             * @description Ora locale di scatto, senza data né fuso
             */
            taken_time: string | null;
            /** Thumb Url */
            thumb_url: string;
            /** Display Url */
            display_url: string;
        };
        /** SharedSegment */
        SharedSegment: {
            /**
             * From Stop Id
             * Format: uuid
             */
            from_stop_id: string;
            /**
             * To Stop Id
             * Format: uuid
             */
            to_stop_id: string;
            transport_mode: components["schemas"]["TransportMode"];
            /** Duration Min */
            duration_min: number | null;
        };
        /** SharedStop */
        SharedStop: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            category: components["schemas"]["StopCategory"];
            /** Custom Category */
            custom_category: string | null;
            /**
             * Time
             * @description Orario mostrato: effettivo o pianificato secondo il viaggio
             */
            time: string | null;
            time_precision: components["schemas"]["TimePrecision"];
            /** Duration Min */
            duration_min: number | null;
            /** Notes */
            notes: string | null;
        };
        /** SharedTrip */
        SharedTrip: {
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            kind: components["schemas"]["TripKind"];
            /** Cover Url */
            cover_url: string | null;
            /** Stop Count */
            stop_count: number;
            /** Photo Count */
            photo_count: number;
            /** Days */
            days: components["schemas"]["SharedDay"][];
        };
        /**
         * StopCategory
         * @enum {string}
         */
        StopCategory: "attraction" | "food" | "hotel" | "transport" | "parking" | "nature" | "shopping" | "nightlife" | "custom";
        /** StopCreate */
        StopCreate: {
            /** Name */
            name: string;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Address */
            address?: string | null;
            category?: components["schemas"]["StopCategory"] | null;
            /** Custom Category */
            custom_category?: string | null;
            /** Planned Arrival */
            planned_arrival?: string | null;
            /** Planned Departure */
            planned_departure?: string | null;
            /** Planned Duration Min */
            planned_duration_min?: number | null;
            planned_time_precision?: components["schemas"]["TimePrecision"] | null;
            /** Actual Arrival */
            actual_arrival?: string | null;
            /** Actual Departure */
            actual_departure?: string | null;
            /** Actual Duration Min */
            actual_duration_min?: number | null;
            actual_time_precision?: components["schemas"]["TimePrecision"] | null;
            /** Notes */
            notes?: string | null;
            /** External Ref */
            external_ref?: string | null;
            /** Position */
            position?: number | null;
        };
        /** StopOut */
        StopOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Day Id
             * Format: uuid
             */
            day_id: string;
            /** Position */
            position: number;
            /** Name */
            name: string;
            /** Lat */
            lat: number | null;
            /** Lon */
            lon: number | null;
            /** Address */
            address: string | null;
            category: components["schemas"]["StopCategory"];
            /** Custom Category */
            custom_category: string | null;
            /** Planned Arrival */
            planned_arrival: string | null;
            /** Planned Departure */
            planned_departure: string | null;
            /** Planned Duration Min */
            planned_duration_min: number | null;
            planned_time_precision: components["schemas"]["TimePrecision"];
            /** Actual Arrival */
            actual_arrival: string | null;
            /** Actual Departure */
            actual_departure: string | null;
            /** Actual Duration Min */
            actual_duration_min: number | null;
            actual_time_precision: components["schemas"]["TimePrecision"];
            /** Notes */
            notes: string | null;
            /** External Ref */
            external_ref: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** StopUpdate */
        StopUpdate: {
            /** Name */
            name?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Address */
            address?: string | null;
            category?: components["schemas"]["StopCategory"] | null;
            /** Custom Category */
            custom_category?: string | null;
            /** Planned Arrival */
            planned_arrival?: string | null;
            /** Planned Departure */
            planned_departure?: string | null;
            /** Planned Duration Min */
            planned_duration_min?: number | null;
            planned_time_precision?: components["schemas"]["TimePrecision"] | null;
            /** Actual Arrival */
            actual_arrival?: string | null;
            /** Actual Departure */
            actual_departure?: string | null;
            /** Actual Duration Min */
            actual_duration_min?: number | null;
            actual_time_precision?: components["schemas"]["TimePrecision"] | null;
            /** Notes */
            notes?: string | null;
            /** External Ref */
            external_ref?: string | null;
        };
        /**
         * TimePrecision
         * @enum {string}
         */
        TimePrecision: "exact" | "approximate" | "morning" | "afternoon" | "evening" | "unknown";
        /**
         * TransportMode
         * @enum {string}
         */
        TransportMode: "walking" | "subway" | "train" | "bus" | "car" | "taxi" | "bike" | "ferry" | "plane" | "unknown";
        /** TripCreate */
        TripCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** @default plan */
            kind: components["schemas"]["TripKind"];
            /** Timezone */
            timezone?: string | null;
        };
        /** TripDetail */
        TripDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            kind: components["schemas"]["TripKind"];
            visibility: components["schemas"]["Visibility"];
            /** Timezone */
            timezone: string | null;
            /** Cover Photo Id */
            cover_photo_id?: string | null;
            /**
             * Cover Url
             * @description Copertina scelta oppure, in mancanza, la prima foto
             */
            cover_url?: string | null;
            /**
             * Photo Count
             * @default 0
             */
            photo_count: number;
            /** Day Count */
            day_count: number;
            /** Stop Count */
            stop_count: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Share Token */
            share_token: string | null;
            /** Days */
            days: components["schemas"]["DayOut"][];
        };
        /**
         * TripKind
         * @enum {string}
         */
        TripKind: "plan" | "reconstruct";
        /** TripSummary */
        TripSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            kind: components["schemas"]["TripKind"];
            visibility: components["schemas"]["Visibility"];
            /** Timezone */
            timezone: string | null;
            /** Cover Photo Id */
            cover_photo_id?: string | null;
            /**
             * Cover Url
             * @description Copertina scelta oppure, in mancanza, la prima foto
             */
            cover_url?: string | null;
            /**
             * Photo Count
             * @default 0
             */
            photo_count: number;
            /** Day Count */
            day_count: number;
            /** Stop Count */
            stop_count: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TripUpdate */
        TripUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            kind?: components["schemas"]["TripKind"] | null;
            /** Timezone */
            timezone?: string | null;
            /** Cover Photo Id */
            cover_photo_id?: string | null;
        };
        /** UploadError */
        UploadError: {
            /** Filename */
            filename: string;
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Variant
         * @enum {string}
         */
        Variant: "thumb" | "display" | "original";
        /**
         * Visibility
         * @enum {string}
         */
        Visibility: "private" | "unlisted";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    public_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicConfig"];
                };
            };
        };
    };
    list_trips_api_trips_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripSummary"][];
                };
            };
        };
    };
    create_trip_api_trips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trip_api_trips__trip_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_trip_api_trips__trip_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_trip_api_trips__trip_id__patch: {
        parameters: {
            query?: {
                /** @description Conferma l'eliminazione di giorni che contengono tappe */
                confirm_delete_days?: boolean;
            };
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_days_api_trips__trip_id__days_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_day_api_days__day_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DayUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_stop_api_days__day_id__stops_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_stops_api_days__day_id__reorder_stops_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderStops"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_stop_api_stops__stop_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stop_api_stops__stop_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stop_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_stop_api_stops__stop_id__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stop_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveStop"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_segment_api_segments__segment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                segment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_photos_api_trips__trip_id__photos_get: {
        parameters: {
            query?: {
                day_id?: string | null;
                stop_id?: string | null;
                /** @description Solo foto senza giorno */
                unassigned?: boolean;
            };
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_photos_api_trips__trip_id__photos_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_photos_api_trips__trip_id__photos_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoUploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_by_date_api_trips__trip_id__photos_assign_by_date_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignByDateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_photo_api_photos__photo_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_photo_api_photos__photo_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhotoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    photo_file_api_photos__photo_id__file_get: {
        parameters: {
            query?: {
                size?: components["schemas"]["Variant"];
            };
            header?: never;
            path: {
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_share_api_trips__trip_id__share_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_share_api_trips__trip_id__share_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_share_api_trips__trip_id__share_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotate_share_api_trips__trip_id__share_rotate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shared_trip_api_share__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharedTrip"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shared_photo_api_share__token__photos__photo_id__get: {
        parameters: {
            query?: {
                size?: components["schemas"]["Variant"];
            };
            header?: never;
            path: {
                token: string;
                photo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_geocode_search_get: {
        parameters: {
            query: {
                q: string;
                lat?: number | null;
                lon?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
